### ISSUE TITLE
Englisch Documentation / Naming

### ISSUE THREAD

**Issue by janwirth** [isellsoap/deutschlandGeoJSON#1]
Even though this is about Germany, non-German-speakers may be interested in this data too.

**Comment by isellsoap** [comment]
Sorry for replying this late, somehow I don’t get notifications for newly created issues. I will translate the README.md during next week. Thanks for opening this issue!

**Comment by janwirth** [comment]
Did you unwatch the repo by accident?

**Comment by nick202325** [comment]
I just added a PR with translation of the README file to English [i18n English README](https://github.com/isellsoap/deutschlandGeoJSON/pull/5).

**Comment by isellsoap** [comment]
Fixed with https://github.com/isellsoap/deutschlandGeoJSON/pull/5. Thanks, @mibrl12!
