### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by exandi** [isellsoap/deutschlandGeoJSON#13]
Hey,
thanks for you very nice repo!
I just found out, that the ids in you data are ongoning numbers and not the Kreisgemeinde IDs. So I found the Dataset:
https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete.html

what I think: this data could be extended to contain the Kreisgemeinde ID, so if you have Data from a Kreisgemeine you are able to plot them with plotly.

Hope that helps you!?

Regards

**Comment by isellsoap** [comment]
Hi @exandi, thanks for opening the issue. This project will be archived, because I won’t be able to maintain it anymore. Feel free to fork it and make it your own. Thanks a lot.
