### ISSUE TITLE
TopoJSON

### ISSUE THREAD

**Issue by usolomer** [isellsoap/deutschlandGeoJSON#2]
Danke, eine sehr hilfreiche Sammlung. Ein Ergänzungswunsch trotzdem:

Es wären alternative Versionen im TopoJSON-Format nützlich. Ich beziehe mich dabei auf die Artikel [https://bost.ocks.org/mike/map/](url) und [https://github.com/mbostock/topojson/wiki](url)

**Comment by isellsoap** [comment]
Hallo @usolomer, danke für den Vorschlag. Kann man relativ einfach [mit der CLI von `topojson-server`](https://github.com/topojson/topojson-server/blob/master/README.md#command-line-reference) erledigen. Hilft dir das weiter?

Sorry für die seeehr späte Antwort…
