### ISSUE TITLE
Lörrach contains new line and a duplicate

### ISSUE THREAD

**Issue by fritzmg** [isellsoap/deutschlandGeoJSON#3]
The Landkreis "Lörrach" contains the following for `NAME_3`:
```
Lörrach\n 
Lörrach\n
```
instead of just `Lörrach`. At least in `4_niedrig.geojson`.

**Comment by isellsoap** [comment]
@fritzmg Fixed with https://github.com/isellsoap/deutschlandGeoJSON/commit/ada0aacb3d22d0a1b466d99a28dedff4acfc0652. Nice catch, thanks for this!
