### ISSUE TITLE
better Bundesländer feature props

### ISSUE THREAD

**Issue by derhuerst** [isellsoap/deutschlandGeoJSON#7]
What do you think about the following proposals?

1. In `2_bundeslaender/*.geojson`, use [ISO_3166-2:DE](https://en.wikipedia.org/wiki/ISO_3166-2:DE) as `id`s and [their number from the *Gemeindeschlüssel*](https://de.wikipedia.org/wiki/Amtlicher_Gemeindeschlüssel#Länder_der_Bundesrepublik_Deutschland) as `nr`.
2. In `2_bundeslaender/*.geojson`, drop all properties related to the country, as they're confusing when handling data on this level, and keep only `name` (formerly `NAME_1`) and `type` (formerly `ENGTYPE_1`).
3. Version this dataset according to [SemVer](https://semver.org), using Git tags (which are also reflected as GitHub releases)?

**Comment by derhuerst** [comment]
Will implement `1` and `2` in my fork.

**Comment by isellsoap** [comment]
Sounds good. Thanks a lot for your efforts! I will merge your PR. Sorry for getting so late to you about this.

**Comment by isellsoap** [comment]
Regarding request number 3: I’m aware of semver, I will see what I can do (if I find the time to set this up properly). Thanks for the good suggestions.
