### ISSUE TITLE
PLZ areas

### ISSUE THREAD

**Issue by maxnoe** [isellsoap/deutschlandGeoJSON#9]
Would be awesome if these where also available.

Shapefile available here: https://www.suche-postleitzahl.org/downloads

**Comment by isellsoap** [comment]
In what form would you want the PLZ to be available? As a key-value-pair inside the appropriate objects?

**Comment by maxnoe** [comment]
They are also shapes, just like the Bundesländer or Regierungsbezirke

**Comment by maxnoe** [comment]
This is about the *area* belonging to one PLZ code. 

See for example: https://github.com/maxnoe/plz_plot

**Comment by isellsoap** [comment]
very nice! I’ll look into it.

**Comment by isellsoap** [comment]
Their interactive cart creation tool is pretty cool: https://www.suche-postleitzahl.org/plz-karte-erstellen
I’m not sure if it makes sense to integrate something static into this repository, when there is such a good alternative. What do you think?

**Comment by maxnoe** [comment]
Oh, that's new. Awesome
